jobs:
  release-file-system-image:
    uses: r-wasm/actions/.github/workflows/release-file-system-image.yml@v2
    with:
      compress: false
    permissions:
      contents: write
      repository-projects: read
