on:
  workflow_dispatch:

name: pkgdown

jobs:
  repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build wasm packages
      uses: r-wasm/actions/build-rwasm@v2
      with:
        packages: |
          gradebook

    # Use repository files in `./_site` directory to create a GitHub Pages site.
